---
- name: Initialize repo
  shell: git init /opt/mongo-mapreduce-sdk-python
  args:
    chdir: /opt

- name: Checkout empty branch
  shell: git checkout -B empty
  args:
    chdir: /opt/mongo-mapreduce-sdk-python

- name: Copy repo
  local_action: shell git push ssh://root@{{ inventory_hostname }}:/opt/mongo-mapreduce-sdk-python master

- name: Checkout master branch
  shell: git checkout master
  args:
    chdir: /opt/mongo-mapreduce-sdk-python

- name: Check for docker
  shell: docker ps -a
  register: docker_rc
  ignore_errors: yes

- name: Run docker install
  shell: chmod +x get-docker.sh && ./get-docker.sh
  args:
    chdir: /opt/mongo-mapreduce-sdk-python/ansible/roles/docs/files
  when: docker_rc.rc != 0

- name: Install pip3
  shell: apt-get install -y python3-pip

- name: Install docker compose
  shell: pip3 install docker-compose

- name: Copy SSL Certs
  copy:
    src: /etc/ssl/private/docs.mreduce.com
    dest: /etc/ssl/private

- name: Run docker-compose up
  shell: docker-compose -f docker/docker-compose-prod.yml up -d --build
  args:
    chdir: /opt/mongo-mapreduce-sdk-python  


